### PR TITLE
Param gov config changes

### PR DESCRIPTION
**Pull request by masayafunakoshi1**
Added new tracking tab, separating proposal count info into there.

https://user-images.githubusercontent.com/59552589/160263723-55f83daf-0952-4e9e-8029-fe1370f89ccb.mp4

Using guard clauses and created separate components for each tab.

guardClauseChanges

### CODE REVIEW

**Comment by masayafunakoshi1** [comment]
> @SebastianBor 
So you want the label to be hidden if there are "0" of something? I'll make those changes!

**Comment by abrzezinski94** [comment]
please fix one import at accountsview and it will be good to go :D import { AccountType } from '@utils/uiTypes/assets'

**Comment by SebastianBor** [comment]
It throws error when you select the `Accounts` tab

**Comment by masayafunakoshi1** [comment]
Created new branch because I messed up rebasing/merging.
https://github.com/solana-labs/governance-ui/pull/585

Thank you for the reviews! @SebastianBor @abrzezinski94

**Pull request closed without merging**
