### PR TITLE
Mean: Use latest payment streaming package

### PR DESCRIPTION
**Pull request by welldan97**
Hello! 
I'm updating mean streaming proposals to use the latest version of @mean-dao/payment-streaming. There are a few breaking changes in it, mostly related to renaming

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204237793529847

### CODE REVIEW

**Comment by eydelrivero** [comment]
@welldan97 payment-streaming SDK dependency can be updated to stable v4.0.0 now.

**Comment by welldan97** [comment]
Hi @abrzezinski94, we updated the our meanfi SDK package, and here I'm applying the changes for relevant meanfi integration. Can you review, please

**Comment by welldan97** [comment]
Hi, @abrzezinski94!

Just wanted to check in on the pull request I submitted a few months ago. I was hoping to see if there's any progress or feedback on it.

Let me know if there's anything else I can provide or do to help move things along. Thanks a lot for your time, and looking forward to hearing from you!

**Comment by welldan97** [comment]
@nramadas, @asktree , @SebastianBor I know you are very busy, yet can we push this through? There are just updates to mean streaming sdk, nothing more. We would need this updates for further prs

**Comment by abrzezinski94** [comment]
> @nramadas, @asktree , @SebastianBor I know you are very busy, yet can we push this through? There are just updates to mean streaming sdk, nothing more. We would need this updates for further prs

Ah hello please resolve conflicts and ill merge it immediately

**Comment by welldan97** [comment]
Thank you so much @abrzezinski94, that was fast

**Pull request merged**
