### PR TITLE
refactor (away) useWalletStore and others

### PR DESCRIPTION
**Pull request by asktree**
This refactor removes everything from `useWalletStore` that isn't wallet related, though soon I'll probably even remove that-- we just use solana's package anyway.

It also removes most things from `useRealm`, and kills `useProposal`.

Everything is replaced with `react-query` hooks. 

This refactor also resolves a large number of exhaustive deps warnings. I will probably not do another refactor before eliminating nearly all warnings of this nature, issues caused by them were a massive headache.

I also make it where any transaction being sent will invalidate all writable pubkeys for query keys.

### CODE REVIEW

**Comment by abrzezinski94** [comment]
when you withdraw tokens from lock tokens page it dont refresh after the tx 
Zrzut ekranu 2023-05-25 o 16 05 50

**Comment by abrzezinski94** [comment]
When you connect your wallet and switch to other one you need to reconnect again

**Comment by abrzezinski94** [comment]
when you vote vote count dont refresh 
Zrzut ekranu 2023-05-25 o 16 13 15

**Comment by asktree** [comment]
@abrzezinski94 I went in and fixed all the spots where batch queries need to be invalidated (proposals, token accounts), by looking at all the actions from useWalletStore I'd deleted. (whoops)

I also think I fixed the program version not defined issue, and some race conditions. I suspect the not being able to vote issue is a race condition that I fixed, but I can't be sure. Could you check again?

**Comment by abrzezinski94** [comment]
now sometimes page got loop spam request also community votes in delegate looks weird 
Zrzut ekranu 2023-05-28 o 12 19 38

**Comment by abrzezinski94** [comment]
before refactor to load mango dao there was around ~200 requests atm to load page it takes around ~400 for mango dao

**Comment by abrzezinski94** [comment]
when you select delegate it start to loop spam requestes

**Comment by abrzezinski94** [comment]
still got same problem when i click lock tokens 
Zrzut ekranu 2023-05-28 o 12 22 38

**Comment by asktree** [comment]
@abrzezinski94 I fixed the lock tokens issue

**Comment by asktree** [comment]
@abrzezinski94 ok fixed all issues. current number of requests to load mngo with your wallet is 230.

**Pull request merged**
