### PR TITLE
Introduce packages and rework instruction type selection

### PR DESCRIPTION
**Pull request by GregoryNEUT**
There are many instructions, and much more to come. One simple select listing all existing instructions is not enough.

What is done with this PR:

1. Introduce the concept of package to regroup instructions (Solend, Friktion, Mango, etc.)
2. update the instruction type select to work in two steps:
- first, select the package
- second, select the instruction type.

Result:

https://user-images.githubusercontent.com/22965416/199989755-fce10912-9192-4da3-8f99-38a22ae47c74.mov

Specifics:
- If a logo is associated to a package display it, otherwise display the package's name
- It's now possible to apply symbol filtering at package level I.e `symbol === 'MNGO'`
- If someone declare a new instruction in the `enum Instructions`, typescript automatically shows an error saying informations are missing:
- logo have been minified using `optipng -o7` CLI program on macosx

Screenshot 2022-11-04 at 17 02 13

@abrzezinski94

### CODE REVIEW

**Comment by abrzezinski94** [comment]
hi please fix yarn build 
Zrzut ekranu 2022-11-5 o 12 19 23

**Comment by GregoryNEUT** [comment]
hm I commited my video test instruction 

```
MyNewAwmazingInstruction,
```

Well it proves that linting works when you forget to add infos about new instruction :')

**Comment by GregoryNEUT** [comment]
Not sure why the yarn test-all fail tho:

```
[2/4] Fetching packages...
error https://registry.yarnpkg.com/@stablelib/bytes/-/bytes-1.0.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "EEXIST: file already exists, mkdir '/home/runner/.cache/yarn/v6/npm-@stablelib-bytes-1.0.1-0f4aa7b03df3080b878c7dea[9](https://github.com/solana-labs/governance-ui/actions/runs/3390119684/jobs/5633896796#step:4:10)27d01f42d6a20d8-integrity/node_modules/@stablelib/bytes/lib'"
```

**Comment by abrzezinski94** [comment]
> 

Ye if you re run te test it will work this is some problem with @stablelib/bytes/-/bytes-1.0.1.tgz it randomly throws 404 same locally if you ping the npm package site.

**Comment by abrzezinski94** [comment]
Ill look soon at the code it will also need @SebastianBor look too.

**Comment by GregoryNEUT** [comment]
> Ill look soon at the code it will also need @SebastianBor look too.

Perfect thx! :)

**Comment by abrzezinski94** [comment]
All good from my side we need to wait for @SebastianBor

**Review by nramadas — APPROVED** [review]
LGTM

**Comment by GregoryNEUT** [comment]
https://user-images.githubusercontent.com/22965416/203773901-d5dbca40-c3f5-4512-bd11-ec1822f72fa5.mov

**Comment by GregoryNEUT** [comment]
Following feedback, adapted packages:


https://user-images.githubusercontent.com/22965416/203916915-03f27b34-2aa5-4a68-a2a8-8e74afd2a3f7.mov

**Pull request merged**
