### PR TITLE
Add custom deposit amounts

### PR DESCRIPTION
**Pull request by Flaque**
Revives #38 since it seems like Max's comment (https://github.com/blockworks-foundation/governance-ui/pull/38#issuecomment-936563566) here has been resolved by @SebastianBor's [commit](https://github.com/solana-labs/solana-program-library/commit/dc7f6be0347a89f9f29d4f5bdd1baa030c48ba5e#diff-40ea569c8e8ae8480ead06c47c179a25d98df9104b38cfce347dc784f9cf0fe1).

Opening this as a draft while I test it a bit.

Co-authored-by: saml33 <30796577+saml33@users.noreply.github.com>
Co-authored-by: flaque <evan@roomservice.dev>

### CODE REVIEW

**Comment by Flaque** [comment]
I love the GUI @saml33! The % is a nice touch. 

Screen Shot 2021-12-08 at 2 46 52 PM

**Comment by mschneider** [comment]
@SebastianBor happy to merge this if it works out of the box. but not sure if would we need to upgrade the mango governance program, for this to work?

**Comment by SebastianBor** [comment]
> @SebastianBor happy to merge this if it works out of the box. but not sure if would we need to upgrade the mango governance program, for this to work?

No, it won't work, we need v2 for this

**Comment by asktree** [comment]
I am probably going to close this due to age and lack of context.

**Comment by asktree** [comment]
@mschneider @SebastianBor is this still relevant in 2023?

**Comment by SebastianBor** [comment]
> @mschneider @SebastianBor is this still relevant in 2023?

It's an old PR but it's still relevant in terms of functionality. spl-gov didn't support custom deposit amount at that time and this is why it was put on hold. 
However I think we can close this one because I wouldn't put the prompt by default when depositing tokens. That could be done as advance option from the 'My governance power' details view instead.

**Pull request closed without merging**
