### PR TITLE
Add support for SOL Treasury's owned token accounts

### PR DESCRIPTION
**Pull request by tomjohn1028**
In this PR:
* Native SOL Treasury Accounts will display their owned Token Accounts
* A more generic send token component that has a less coupled state
* Creating a proposal to transfer tokens from one of these owned accounts

Out of the scope of this PR _separate issues should be made if this PR is accepted as is_
* Writing the DRYest code...sorry new to the code base and couldn't spend the time refactoring :) 
* Summing the token accounts for the Treasuries total ownership

### CODE REVIEW

**Review by abrzezinski94 — APPROVED** [review]

**Comment by abrzezinski94** [comment]
One thing i notice now that when you click send on ata account it opens SOL modal now. Maybe some merge broke something ?

**Comment by tomjohn1028** [comment]
> One thing i notice now that when you click send on ata account it opens SOL modal now. Maybe some merge broke something

Ah yeah you're right. I need to switch out that component that relies on the governance token account

**Comment by abrzezinski94** [comment]
I found one problem with validation

**Comment by tomjohn1028** [comment]
@abrzezinski94 I've been having intermittent issues with GitHub this morning and it still shows the merge conflict is unresolved. I'll tag you when I get an verified fixed

**Comment by tomjohn1028** [comment]
@abrzezinski94 I'm not seeing any errors on my end. Proposals are generating fine. Are you able to pull and try again?

**Pull request merged**
