### PR TITLE
Update Dao Charter

### PR DESCRIPTION
**Pull request by TWONAEW**

### CODE REVIEW

**Comment by jennifer-notifi** [comment]
@TWONAEW Can you please add a comment description with what you are updating and do a `git rebase main` to address deployment errors?

**Comment by TWONAEW** [comment]
@jennifer-notifi updating - Add images to DAO from folder /public/realms/OCD/ 

Still a learner on github so not sure what this means... git rebase main ?

**Comment by jennifer-notifi** [comment]
> @jennifer-notifi updating - Add images to DAO from folder /public/realms/OCD/
> 
> Still a learner on github so not sure what this means... git rebase main ?

Hey there! Originally, it looked like the checks in the PR were failing because there was a bug in your PR that was fixed using this PR: https://github.com/solana-labs/governance-ui/commit/d08838752e21394def2772b60392b092d15e3292

If you want to update your PR to sync with the latest updates in the main branch, you should do:

```
git checkout main
git pull main
git rebase main
```

I think you resolved the original issue but some repo checks are still failing. Can you please go to this section:

Screen Shot 2022-09-06 at 6 02 59 PM

With anything with an X next to it, can you please check on Details and then read through what are causing the errors and address them?

**Comment by TWONAEW** [comment]
@jennifer-notifi   did a rebase as suggested and looked at the errors..

They both report - Error: Process completed with exit code 1.
Wouldn't know what to look at to address them...

**Pull request closed without merging**
