### PR TITLE
upgrading Profile pic

### PR DESCRIPTION
**Pull request by DimiMili**
upgrading Profile pic

### CODE REVIEW

**Review by SebastianBor — COMMENTED** [review]
It looks like there are 2 extra unnecessary icons. Do we need 3 of them?

**Comment by DimiMili** [comment]
No we do not need 3 of them. We just need one. I mistakenly uploaded more than once.

**Comment by SebastianBor** [comment]
> No we do not need 3 of them. We just need one. I mistakenly uploaded more than once.

ok, then please remove the extra pictures from the PR or create a new one with just the picture which is needed

**Comment by DimiMili** [comment]
I think I deleted them. (first time i'm doing sth like this). Let me know if it's ok now.

**Comment by SebastianBor** [comment]
> I think I deleted them. (first time i'm doing sth like this). Let me know if it's ok now.

Almost there :) There is still one extra public/GrapeCCSubDAO/GrapeCCSubDAO.png

**Pull request merged**
