### PR TITLE
Updated image file ext to .png

### PR DESCRIPTION
**Pull request by CreatedbyIO**

### CODE REVIEW

**Comment by SebastianBor** [comment]
Please fix the merge conflicts

**Comment by CreatedbyIO** [comment]
Hi Sebastian,

Thanks for all you help with this. Quick question on the final commit 
merge, do I select

Commit updates to the main branch

or

Create a new branch and commit updates.

Tom

**Comment by SebastianBor** [comment]
> Hi Sebastian, Thanks for all you help with this. Quick question on the final commit merge, do I select Commit updates to the main branch or Create a new branch and commit updates. Tom

I'm assuming you are on your fork's main branch so it should be update to the main branch

**Comment by CreatedbyIO** [comment]
Thank you. Have a good one!

**Comment by CreatedbyIO** [comment]
Sorry for all the questions, I've never done a merge before on Github so 
please bare with me. Is there any instructions you can point me to to 
achieving the merge to fix the broken file. What I have found seems to 
be incorrect. Thank you so much for your help and time.

**Pull request merged**
